### ISSUE TITLE
Qt 5.11.1 fails to build with Visual Studio 15.9.5

### ISSUE THREAD

**Issue by Knitschi** [hunter-packages/Qt#18]
This is the same as ruslo/hunter/issues/1702

This is probably a problem of Qt and not of the package, but I am mentioning it here anyways.
This is the compiler error message.
```
error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.
```

Maybe Qt 5.12 fixes the problem.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
